name: Drysdale-Wilson Website

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

env:
  AWS_DEFAULT_REGION: eu-west-1

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Deploy
        run: aws s3 sync ./src s3://drysdale-wilson-website
